# Generated by Django 4.2.15 on 2024-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_image', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('genres', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Horror', 'Horror')], max_length=7)),
            ],
        ),
    ]
